steps:
  # FIXME only rebuild image when necessary ann delete previous version from gcr
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     ['build', '-t', 'gcr.io/centsideas/bazelisk', '-f', 'misc/images/bazelisk.Dockerfile', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/centsideas/bazelisk']

  # - name: gcr.io/centsideas/bazelisk
  #   args: ['test', '//services/consumer/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//services/gateway/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//services/ideas/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//services/reviews/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//services/users/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//services/notifications/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//services/admin/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//packages/event-sourcing/...']

  - name: gcr.io/centsideas/bazelisk
    args: ['test', '//packages/utils/...']
timeout: 3600s
#options:
#  machineType: "N1_HIGHCPU_8"
