apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: registry.hub.docker.com/flolu/cents-ideas_consumer:0.3.1
          envFrom:
            - configMapRef:
                name: global-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-consumer
spec:
  selector:
    app: consumer
  ports:
    - name: http
      port: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projection-database
spec:
  selector:
    matchLabels:
      app: projection-database
  replicas: 1
  template:
    metadata:
      labels:
        app: projection-database
    spec:
      containers:
        - name: projection-database
          image: mongo:4.0
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: projection-database-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-projection-database
spec:
  selector:
    app: projection-database
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
