apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideas-deployment
spec:
  selector:
    matchLabels:
      app: ideas
  replicas: 1
  template:
    metadata:
      labels:
        app: ideas
    spec:
      containers:
        - name: ideas
          image: registry.hub.docker.com/flolu/cents-ideas_ideas:0.3.2
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config

---
apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-ideas
spec:
  selector:
    app: ideas
  ports:
    - name: http
      port: 3000
  type: ClusterIP
