apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideas-event-store-deployment
spec:
  selector:
    matchLabels:
      app: ideas-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: ideas-event-store
    spec:
      containers:
        - name: ideas-event-store
          image: mongo:4.0
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: ideas-event-store-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-ideas-event-store
spec:
  selector:
    app: ideas-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
