apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
spec:
  selector:
    matchLabels:
      app: reviews
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: registry.hub.docker.com/flolu/cents-reviews_reviews:0.3.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
          readinessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: cents-reviews-reviews
spec:
  selector:
    app: reviews
  ports:
    - name: http
      port: 3000
  type: ClusterIP
