apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  ENV: dev

  GATEWAY_URL: https://api.centsideas.com
  MAIN_CLIENT_URL: https://centsideas.com

  IDEAS_SERVICE_HOST: centsideas-ideas:3000
  CONSUMER_SERVICE_HOST: centsideas-consumer:3000
  USERS_SERVICE_HOST: centsideas-users:3000
  REVIEWS_SERVICE_HOST: centsideas-reviews:3000
  NOTIFICATIONS_SERVICE_HOST: centsideas-notifications:3000
  ADMIN_SERVICE_HOST: centsideas-admin:3000

  IDEAS_DATABASE_URL: mongodb://centsideas-reviews-event-store:27017
  REVIEWS_DATABASE_URL: ${REVIEWS_DATABASE_URL}
  PROJECTION_DATABASE_URL: mongodb://centsideas-projection-database:27017
  USERS_DATABASE_URL: mongodb://centsideas-users-event-store:27017
  NOTIFICATIONS_DATABASE_URL: mongodb://centsideas-notifications-event-store:27017
  ADMIN_DATABASE_URL: mongodb://centsideas-admin-database:27017

  KAFKA_ADVERTISED_HOST_NAME: 172.31.25.198
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
  KAFKA_ADVERTISED_PORT: 9092
  KAFKA_BROKER_HOST: kafka-service:9092

  VAPID_PUBLIC_KEY: ___
