apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: centsideas-ingress
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - centsideas.com
        - api.centsideas.com
        - admin.centsideas.com
        - socket.admin.centsideas.com
      secretName: centsideas-tls
  rules:
    - host: api.centsideas.com
      http:
        paths:
          - backend:
              serviceName: centsideas-gateway
              servicePort: 3000
    - host: centsideas.com
      http:
        paths:
          - backend:
              serviceName: centsideas-client
              servicePort: 8080
    - host: admin.centsideas.com
      http:
        paths:
          - backend:
              serviceName: centsideas-admin-client
              servicePort: 8080
    - host: socket.admin.centsideas.com
      http:
        paths:
          - backend:
              serviceName: centsideas-admin
              servicePort: 3000
