apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: centsideas-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: 'nginx'
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - localhost
        - api.localhost
      # secretName: centsideas-tls
  rules:
    - host: api.localhost
      http:
        paths:
          - backend:
              serviceName: centsideas-gateway
              servicePort: 3000
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: centsideas-client
              servicePort: 8080
# ---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: centsideas-ingress
#   namespace: ingress-nginx
# data:
#   # FIXME I am not sure if this actually works, because it makes no differnce even when turned off
#   use-gzip: 'true'
