apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - localhost
        - api.localhost
  rules:
    - host: api.localhost
      http:
        paths:
          - backend:
              service:
                name: gateway
                port:
                  number: 3000
            path: /
            pathType: Prefix
