apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideas-deployment
spec:
  selector:
    matchLabels:
      app: ideas
  replicas: 1
  template:
    metadata:
      labels:
        app: ideas
    spec:
      containers:
        - name: ideas
          image: gcr.io/cents-ideas/ideas:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
          readinessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
