apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideas-deployment
spec:
  selector:
    matchLabels:
      app: ideas
  replicas: 1
  template:
    metadata:
      labels:
        app: ideas
    spec:
      containers:
        - name: ideas
          image: ideas:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: centsideas-ideas
spec:
  selector:
    app: ideas
  ports:
    - name: http
      port: 3000
    - name: grpc
      port: 40000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideas-event-store-deployment
spec:
  selector:
    matchLabels:
      app: ideas-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: ideas-event-store
    spec:
      containers:
        - name: ideas-event-store
          image: mongo:4.2.6
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          # resources:
          #   requests:
          #     memory: 100Mi
          #     cpu: 50m
          #   limits:
          #     memory: 500Mi
          #     cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: ideas-event-store-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: centsideas-ideas-event-store
spec:
  selector:
    app: ideas-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
