steps:
  # - id: "unit tests"
  #   name: gcr.io/cloud-builders/bazel
  #   args:
  #     [
  #       "test",
  #       "--remote_cache=https://storage.googleapis.com/cents-ideas-bazel-cache",
  #       "--google_default_credentials",
  #       "--test_output=errors",
  #       "//...",
  #     ]

  - id: "apply to kubernetes"
    # name: gcr.io/cloud-builders/bazel
    name: eu.gcr.io/cents-ideas/slim-bazel-kubectl
    entrypoint: /bin/sh
    args:
      - |
        gcloud container clusters get-credentials cents-ideas --zone=europe-west3-a --project=cents-ideas
        bazel run //:kubernetes.apply
