steps:
  - id: "unit tests"
    name: gcr.io/cloud-builders/bazel
    args:
      [
        "test",
        "--google_default_credentials",
        "//...",
        "--",
        "-services/client/...",
      ]
timeout: 3600s
#options:
#  machineType: 'N1_HIGHCPU_8'
