steps:
  #- name: gcr.io/cloud-builders/bazel
  #  args:
  #    [
  #      "test",
  #      "--remote_cache=https://storage.googleapis.com/cents-ideas-bazel-cache",
  #      "--google_default_credentials",
  #      "--test_output=errors",
  #      "//...",
  #    ]

  - id: "push docker images and deploy changes to kubernetes"
    name: gcr.io/cloud-builders/bazel
    entrypoint: /bin/bash
    args:
      [
        "bazel",
        "run",
        "--remote_cache=https://storage.googleapis.com/cents-ideas-bazel-cache",
        "--google_default_credentials",
        "--test_output=errors",
        "//:kubernetes",
        " > kubernetes.yaml",
      ]

  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "kubernetes.yaml"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-west3-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=cents-ideas"
