steps:
  - id: 'unit tests'
    name: gcr.io/cloud-builders/bazel
    args: [
        'test',
        #"--remote_cache=https://storage.googleapis.com/cents-ideas-bazel-cache",
        #'--test_output=errors',
        '--',
        '//...',
        '-services/client/...',
        '--google_default_credentials',
      ]
