steps:
  - id: 'run unit tests'
    name: gcr.io/cloud-builders/bazel
    args: ['test', '//...']

  - id: 'push docker images and deploy changes to kubernetes'
    name: gcr.io/cloud-builders/bazel
    args: ['run', '//:deployments']

  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://cents-ideas-build-cache/results.zip', 'previous_results.zip']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'new_results.zip', 'gs://cents-ideas-build-cache/results.zip']
