version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092:9092
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none

  gateway:
    build:
      context: ./
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./services/gateway:/usr/app/src/services/gateway
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: .env
    healthcheck:
      test: curl -sS http://127.0.0.1:3000/alive || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  ideas:
    build:
      context: ./
      dockerfile: ./services/ideas/Dockerfile
    volumes:
      - ./services/ideas:/usr/app/src/services/ideas
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: .env
  ideas-event-store:
    image: mongo:4.2
    logging:
      driver: none

  reviews:
    build:
      context: ./
      dockerfile: ./services/reviews/Dockerfile
    volumes:
      - ./services/reviews:/usr/app/src/services/reviews
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: .env
  reviews-event-store:
    image: mongo:4.2
    logging:
      driver: none

  users:
    build:
      context: ./
      dockerfile: ./services/users/Dockerfile
    volumes:
      - ./services/users:/usr/app/src/services/users
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: .env
  users-event-store:
    image: mongo:4.2
    logging:
      driver: none

  consumer:
    build:
      context: ./
      dockerfile: ./services/consumer/Dockerfile
    volumes:
      - ./services/consumer:/usr/app/src/services/consumer
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: .env
  projection-database:
    image: mongo:4.2
    logging:
      driver: none
