version: "3"
services:
  # kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092:9092
    env_file: ./env/.env.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none

  # gateway
  gateway:
    build:
      context: ./
      dockerfile: ./docker/gateway/dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./services/gateway:/usr/app/src/services/gateway
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: ./env/.env.dev

  # consumer
  consumer:
    build:
      context: ./
      dockerfile: ./docker/consumer/dev.Dockerfile
    volumes:
      - ./services/consumer:/usr/app/src/services/consumer
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: ./env/.env.dev
  projection-database:
    image: mongo:4.2
    logging:
      driver: none

  # ideas
  ideas:
    build:
      context: ./
      dockerfile: ./docker/ideas/dev.Dockerfile
    volumes:
      - ./services/ideas:/usr/app/src/services/ideas
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: ./env/.env.dev
  ideas-event-store:
    image: mongo:4.2
    logging:
      driver: none
