version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181'
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    hostname: kafka
    ports:
      - 9092:9092
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - 'zookeeper'

  gateway:
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./register-aliases.ts:/register-aliases.ts
      - ./services/gateway:/services/gateway
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/gateway
    ports:
      - 3000:3000

  ideas:
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./register-aliases.ts:/register-aliases.ts
      - ./services/ideas:/services/ideas
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/ideas
  ideas-event-store:
    image: mongo:4.2
    logging:
      driver: none

  reviews:
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./register-aliases.ts:/register-aliases.ts
      - ./services/reviews:/services/reviews
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/reviews
  reviews-event-store:
    image: mongo:4.2
    logging:
      driver: none

  users:
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./register-aliases.ts:/register-aliases.ts
      - ./services/users:/services/users
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/users
  users-event-store:
    image: mongo:4.2
    logging:
      driver: none

  consumer:
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./register-aliases.ts:/register-aliases.ts
      - ./services/consumer:/services/consumer
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/consumer
    depends_on:
      - 'kafka'
  projection-database:
    image: mongo:4.2
    logging:
      driver: none
