# FIXME research integration testing (maybe with docker-compose or microk8s)

version: "3"
services:
  gateway:
    container_name: gateway
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./services/gateway:/services/gateway
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/gateway --colors
    ports:
      - 3000:3000

  idea:
    container_name: idea
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./services/idea:/services/idea
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/idea --colors
    depends_on:
      - mongo-database

  idea-read:
    container_name: idea-read
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./services/idea-read:/services/idea-read
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/idea-read --colors
    depends_on:
      - idea
      - mongo-database

  authentication:
    container_name: authentication
    image: node:lts-alpine
    working_dir: /
    volumes:
      - ./package.json:/package.json
      - ./tsconfig.json:/tsconfig.json
      - ./services/authentication:/services/authentication
      - ./packages:/packages
      - ./node_modules:/node_modules
    env_file: .env
    command: yarn run ts-node-dev services/authentication --colors
    depends_on:
      - mongo-database

  mongo-database:
    container_name: mongo-database
    image: mongo:4
    logging:
      driver: none
    ports:
      - 27017:27017
