version: "3"
services:
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./docker/gateway/Dockerfile
    ports:
      - 3000:3000
    env_file: ./env/.env.prod
  ideas:
    container_name: ideas
    build:
      context: ./
      dockerfile: ./docker/ideas/Dockerfile
    env_file: ./env/.env.prod
