version: "3"
services:
  # frontend
  frontend:
    container_name: frontend
    ports:
      - 4000:4000
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile

  # gateway
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./docker/gateway/Dockerfile
    ports:
      - 3000:3000
    env_file: ./env/.env.prod

  # consumer
  consumer:
    container_name: consumer
    build:
      context: ./
      dockerfile: ./docker/consumer/Dockerfile
    env_file: ./env/.env.dev

  # ideas
  ideas:
    container_name: ideas
    build:
      context: ./
      dockerfile: ./docker/ideas/Dockerfile
    env_file: ./env/.env.prod
  ideas-event-store:
    container_name: ideas-event-store
    image: mongo:4.2
    ports:
      - 27017:27017

  # kafka
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092:9092
    env_file: ./env/.env.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
