version: "3"
services:
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./docker/gateway/dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./services/gateway:/usr/app/src/services/gateway
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: ./env/.env.dev

  ideas:
    container_name: ideas
    build:
      context: ./
      dockerfile: ./docker/ideas/dev.Dockerfile
    volumes:
      - ./services/ideas:/usr/app/src/services/ideas
      - ./packages:/usr/app/src/packages
      - ./node_modules:/usr/app/src/node_modules
    env_file: ./env/.env.dev
  ideas-event-store:
    container_name: ideas-event-store
    image: mongo:4.2
    ports:
      - 27017:27017
