apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing-deployment
spec:
  selector:
    matchLabels:
      app: mailing
  replicas: 2
  template:
    metadata:
      labels:
        app: mailing
    spec:
      containers:
        - name: mailing
          image: mailing:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: mailing-config
          env:
            - name: secrets.sendgrid.api
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.sendgrid.api
            - name: secrets.tokens.signin
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.signin
            - name: secrets.tokens.change_email
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.change_email
            - name: secrets.tokens.delete_user
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.delete_user
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
              weight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: mailing-service
spec:
  selector:
    app: mailing
  ports:
    - name: http
      port: 3000
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mailing-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: mailing-deployment
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
---

