apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing-deployment
spec:
  selector:
    matchLabels:
      app: mailing
  replicas: 1
  template:
    metadata:
      labels:
        app: mailing
    spec:
      containers:
        - name: mailing
          image: mailing:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: mailing-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: mailing-service
spec:
  selector:
    app: mailing
  ports:
    - name: http
      port: 3000
  type: ClusterIP
