apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:placeholder_name
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: gateway-config
          env:
            - name: secrets.tokens.access
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.access
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 30Mi
              cpu: 30m
            limits:
              memory: 500Mi
              cpu: 500m
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
              weight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: grpc
      port: 40000
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
---

