apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30000
