apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
spec:
  selector:
    matchLabels:
      app: reviews
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: gcr.io/centsideas/reviews:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
          readinessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-reviews
spec:
  selector:
    app: reviews
  ports:
    - name: http
      port: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-event-store-deployment
spec:
  selector:
    matchLabels:
      app: reviews-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews-event-store
    spec:
      containers:
        - name: reviews-event-store
          image: mongo:4.0
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: reviews-event-store-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cents-reviews-reviews-event-store
spec:
  selector:
    app: reviews-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
