apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user
  replicas: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: user-config
          env:
            - name: secrets.tokens.change_email
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.change_email
            - name: secrets.tokens.delete_user
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.delete_user
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - name: http
      port: 3000
    - name: grpc
      port: 40000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-event-store-deployment
spec:
  selector:
    matchLabels:
      app: user-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: user-event-store
    spec:
      containers:
        - name: user-event-store
          image: mongo:4.2.6
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: user-event-store-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: user-event-store-service
spec:
  selector:
    app: user-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-user-event-store-deployment
spec:
  selector:
    matchLabels:
      app: private-user-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: private-user-event-store
    spec:
      containers:
        - name: private-user-event-store
          image: mongo:4.2.6
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: private-user-event-store-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: private-user-event-store-service
spec:
  selector:
    app: private-user-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
