apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  selector:
    matchLabels:
      app: user
  replicas: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: user-config
          env:
            - name: secrets.tokens.change_email
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.change_email
            - name: secrets.tokens.delete_user
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.delete_user
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - name: http
      port: 3000
    - name: grpc
      port: 40000
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: user-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
