apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
spec:
  selector:
    matchLabels:
      app: authentication
  replicas: 2
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: authentication:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: authentication-config
          env:
            - name: secrets.tokens.refresh
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.refresh
            - name: secrets.tokens.access
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.access
            - name: secrets.tokens.signin
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.signin
            - name: secrets.google.client_id
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.google.client_id
            - name: secrets.google.client_secret
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.google.client_secret
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication
  ports:
    - name: http
      port: 3000
    - name: grpc
      port: 40000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-event-store-deployment
spec:
  selector:
    matchLabels:
      app: authentication-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-event-store
    spec:
      containers:
        - name: authentication-event-store
          image: mongo:4.2.6
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: authentication-event-store-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-event-store-service
spec:
  selector:
    app: authentication-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
