apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-event-store-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
