apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-1
  template:
    metadata:
      labels:
        component: kafka-1
    spec:
      containers:
        - name: kafka-1
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-ip-service:2181
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: $(MY_POD_IP)

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-ip-service
spec:
  type: ClusterIP
  selector:
    component: kafka-1
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
