# rename this file to tsl-secret.yaml and paste you certificate and private key into the data (you need to base64 encode them before inserting)

apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: default
data:
  tls.crt: base64 encoded certificate
  tls.key: base64 encoded private key
type: kubernetes.io/tls
