apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-write
spec:
  selector:
    matchLabels:
      app: auth-write
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-write
    spec:
      containers:
        - name: auth-write
          image: auth-write:placeholder_name
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: config
          resources:
            requests:
              memory: 40Mi
              cpu: 15m
            limits:
              memory: 200Mi
              cpu: 200m
          env:
            - name: secrets.tokens.refresh
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.refresh
            - name: secrets.tokens.access
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.access
            - name: secrets.tokens.emailSignIn
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.emailSignIn
            - name: secrets.google.clientId
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.google.clientId
            - name: secrets.google.clientSecret
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.google.clientSecret
            - name: secrets.eventStore.password
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.eventStore.password
            - name: secrets.sendgrid.key
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.sendgrid.key
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
              weight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: auth-write
spec:
  selector:
    app: auth-write
  ports:
    - name: http
      port: 3000
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-write
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: auth-write
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
