apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-read-deployment
spec:
  selector:
    matchLabels:
      app: user-read
  replicas: 2
  template:
    metadata:
      labels:
        app: user-read
    spec:
      containers:
        - name: user-read
          image: user-read:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: user-read-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: user-read-service
spec:
  selector:
    app: user-read
  ports:
    - name: http
      port: 3000
    - name: grpc
      port: 40000
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-read-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: user-read-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
