apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: flolu/cents-ideas_consumer:latest
          env:
            - name: NODE_ENV
              value: development
            - name: LEVEL
              value: debug
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 172.18.0.1
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181

---
apiVersion: v1
kind: Service
metadata:
  name: cents-ideas_consumer
spec:
  selector:
    app: consumer
  type: ClusterIP
