apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ideas-event-store-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-event-store-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reviews-event-store-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projection-database-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
