apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.hub.docker.com/flolu/cents-ideas_gateway:0.2.1
          env:
            - name: NODE_ENV
              value: development
            - name: LEVEL
              value: debug
            - name: IDEAS_SERVICE_HOST
              value: cents-ideas-ideas:3000
            - name: IDEAS_API_ROOT
              value: ideas

---
apiVersion: v1
kind: Service
metadata:
  name: cents-ideas-gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
