apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cents-ideas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  rules:
    - host: api.cents-ideas.flolu.com
      http:
        paths:
          - backend:
              serviceName: cents-ideas-gateway
              servicePort: 3000
  tls:
    - hosts:
        - cents-ideas.flolu.com
      secretName: cents-ideas-crt
