apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  selector:
    matchLabels:
      app: admin
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: admin:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
          readinessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          # resources:
          #   requests:
          #     memory: 100Mi
          #     cpu: 50m
          #   limits:
          #     memory: 500Mi
          #     cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: centsideas-admin
spec:
  selector:
    app: admin
  ports:
    - name: http
      port: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-database-deployment
spec:
  selector:
    matchLabels:
      app: admin-database
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-database
    spec:
      containers:
        - name: admin-database
          image: mongo:4.2.6
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          # resources:
          #   requests:
          #     memory: 100Mi
          #     cpu: 50m
          #   limits:
          #     memory: 500Mi
          #     cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: amdin-database-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: centsideas-admin-database
spec:
  selector:
    app: admin-database
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
