apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idea-read-pvc
spec:
  storageClassName: idea-read-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-idea-read-pv-volume
spec:
  storageClassName: idea-read-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data/idea-read'
    type: DirectoryOrCreate
