apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-write
spec:
  selector:
    matchLabels:
      app: user-write
  replicas: 2
  template:
    metadata:
      labels:
        app: user-write
    spec:
      containers:
        - name: user-write
          image: user-write:placeholder_name
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: config
          resources:
            requests:
              memory: 60Mi
              cpu: 15m
            limits:
              memory: 300Mi
              cpu: 200m
          env:
            - name: secrets.tokens.emailChange
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.emailChange
            - name: secrets.tokens.userDeletion
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.tokens.userDeletion
            - name: secrets.eventStore.password
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.eventStore.password
            - name: secrets.sendgrid.key
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secrets.sendgrid.key
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
              weight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: user-write
spec:
  selector:
    app: user-write
  ports:
    - name: http
      port: 3000
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-write
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: user-write
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
