apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: users:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
          env:
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: REFRESH_TOKEN_SECRET
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: ACCESS_TOKEN_SECRET
            - name: LOGIN_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: LOGIN_TOKEN_SECRET
            - name: CHANGE_EMAIL_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: CHANGE_EMAIL_TOKEN_SECRET
            - name: SEND_GRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: SEND_GRID_API_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: FRONTEND_SERVER_EXCHANGE_SECRET
              valueFrom:
                secretKeyRef:
                  name: centsideas-secret
                  key: FRONTEND_SERVER_EXCHANGE_SECRET
          readinessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: centsideas-users
spec:
  selector:
    app: users
  ports:
    - name: http
      port: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-event-store-deployment
spec:
  selector:
    matchLabels:
      app: users-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: users-event-store
    spec:
      containers:
        - name: users-event-store
          image: mongo:4.0
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: users-event-store-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: centsideas-users-event-store
spec:
  selector:
    app: users-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP
