apiVersion: apps/v1
kind: Deployment
metadata:
  name: idea-deployment
spec:
  selector:
    matchLabels:
      app: idea
  replicas: 2
  template:
    metadata:
      labels:
        app: idea
    spec:
      containers:
        - name: idea
          image: idea:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: idea-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
              weight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: idea-service
spec:
  selector:
    app: idea
  ports:
    - name: http
      port: 3000
    - name: grpc
      port: 40000
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: idea-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: idea-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
