apiVersion: apps/v1
kind: Deployment
metadata:
  name: idea-deployment
spec:
  selector:
    matchLabels:
      app: idea
  replicas: 2
  template:
    metadata:
      labels:
        app: idea
    spec:
      containers:
        - name: idea
          image: idea:placeholder_name
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: idea-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: idea-service
spec:
  selector:
    app: idea
  ports:
    - name: http
      port: 3000
    - name: grpc
      port: 40000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idea-event-store-deployment
spec:
  selector:
    matchLabels:
      app: idea-event-store
  replicas: 1
  template:
    metadata:
      labels:
        app: idea-event-store
    spec:
      containers:
        - name: idea-event-store
          image: mongo:4.2.6
          volumeMounts:
            - name: persistent-db-storage
              mountPath: /data/db
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 500Mi
              cpu: 500m
      volumes:
        - name: persistent-db-storage
          persistentVolumeClaim:
            claimName: idea-event-store-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: idea-event-store-service
spec:
  selector:
    app: idea-event-store
  ports:
    - name: mongo
      port: 27017
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: idea-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: idea-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
---

